name: monthly lcsh check
on:
  push: 
    branches:
      - testing
# on: 
#   schedule: 
#     - cron: '* 9 15 * *'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  ASSIGNEES: charlottekostelic
jobs:
  monthly-run:
    name: Run monthly LCSH check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create branch, run script
        run: |
          git checkout -b monthly_check_$(date "+%Y%m%d-%H-%M")
          python monthly_lcsh_check.py

      - name: Parse changes
        id: changes
        run: |
          echo "CHANGED=$(grep 'DEBUG - Revised' lcsh.log | grep -Eo '\[.+]$')" >> $GITHUB_OUTPUT
          echo "DEPRECATED=$(grep 'DEBUG - Deprecated' lcsh.log | grep -Eo '\[.+]$')" >> $GITHUB_OUTPUT
          
      - name: Create PR text
        run: |
          PR_CHANGED="### Changed\n
                     + lcsh.log updated with data from workflow run on $(date '+%D')"
          PR_ADDED="\n
                    ### Added\n
                     + New infile is: data/acc_in.csv\n
                     + Old infile is: data/acc_in_$(date '+%Y%m%d')"
          
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "PR_CHANGED" >> $GITHUB_ENV
          echo ${{ toJSON(steps.changes.outputs) != '{ \"CHANGED\":\"\", \"DEPRECATED\":\"\" }' && '$PR_ADDED' }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Issue text
        if: ${{ toJSON(steps.changes.outputs) != '{ \"CHANGED\":\"\", \"DEPRECATED\":\"\" }' }}
        run: |
          ISSUE_CHANGED="### Changed\n
                         + ${{ steps.changes.outputs.CHANGED }}"
          ISSUE_DEPRECATED="### Deprecated\n
                         + ${{ steps.changes.outputs.DEPRECATED }}"
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo ${{ steps.changes.outputs.CHANGED != '{ }' && '$ISSUE_CHANGED' }} >> $GITHUB_ENV
          echo ${{ steps.changes.outputs.DEPRECATED != '{ }' && '$ISSUE_DEPRECATED' }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV