name: monthly lcsh check
on: 
  # schedule: 
  #   - cron: '* 9 9 * *'
  push: 
    branches:
      - main

jobs:
  monthly-run:
    name: Run monthly LCSH check
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set date and branch name
        run: |
          echo "DATE=$(date "+%Y%m")" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(monthly_check_${DATE})" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
          python -m pip install -r requirements.txt

      - name: Create branch
        run: git checkout -b ${BRANCH_NAME}

      - name: Run script
        run: |
          python monthly_lcsh_check.py

      - name: Create issue
        run: |
          git diff --quiet -- data/ || new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --body "$BODY")
        env:
          TITLE: Changes to ACC LCSH
          ASSIGNEES: charlottekostelic
          BODY: |
            ### Changed:
            + Updated list of terms in: data/acc_in.csv
            + See lcsh.log for lists of changed and deprecated terms

      - name: Commit and push changed files
        run: |
          git config user.name "Charlotte Kostelic"
          git config user.email "charlottekostelic@bookops.org"
          git add lcsh.log
          git add data/*
          git commit -a -m "LCSH Check ${DATE}"
          git push --set-upstream origin ${BRANCH_NAME}