name: monthly lcsh check
on:
  push: 
    branches:
      - github-actions
# on: 
#   schedule: 
#     - chron: * 9 1 * *
jobs:
  monthly-run:
    name: Run monthly LCSH check
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
          python -m pip install -r requirements.txt

      - name: Create branch
        run: git checkout -b lcsh_check

      - name: Run script
        run: |
          python monthly_lcsh_check.py

      - name: Create issue
        run: |
          git diff --quiet HEAD main -- data/ || new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --body "$BODY")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: LCSH changed
          ASSIGNEES: charlottekostelic
          BODY: |
            ### Changed:
            + Updated list of terms in: data/acc_in.csv
            + See data/lcsh.log for lists of changed and deprecated terms

      - name: Commit and push changed files
        run: |
          git config user.name "Charlotte Kostelic"
          git config user.email "charlottekostelic@bookops.org"
          git add lcsh.log
          git diff data/
          git add data/*
          git commit -a -m "Monthly LCSH Check"
          git push --set-upstream origin lcsh_check