name: monthly lcsh check
on:
  push: 
    branches:
      - github-actions
# on: 
#   schedule: 
#     - cron: '* 9 15 * *'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  ASSIGNEES: charlottekostelic
jobs:
  monthly-run:
    name: Run monthly LCSH check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create branch, run script
        run: |
          git checkout -b monthly_check_$(date "+%Y%m%d-%H-%M")
          python monthly_lcsh_check.py

      - name: Commit and push changed files
        run: |
          git config user.name "Charlotte Kostelic"
          git config user.email "charlottekostelic@bookops.org"
          git add lcsh.log
          git add data/*
          git commit -a -m "LCSH Check $(date "+%Y%m%d-%H-%M")"

          echo "CHANGED=$(git diff --quiet -- data/ && 'false' || 'true')" >> $GITHUB_ENV

      - name: Parse changes
        if: ${{ '$CHANGED' == 'true' }}
        run: |
          echo "REVISED=$(grep 'DEBUG - Revised' lcsh.log | grep -Eo '\[.+]$')" >> $GITHUB_ENV
          echo "DEPRECATED=$(grep 'DEBUG - Deprecated' lcsh.log | grep -Eo '\[.+]$')" >> $GITHUB_ENV
          
      - name: Create PR text
        run: |
          PR_CHANGED="### Changed\n
                     + lcsh.log updated with data from workflow run on $(date '+%D')"
          PR_ADDED="\n
                    ### Added\n
                     + New infile is: data/acc_in.csv\n
                     + Old infile is: data/acc_in_$(date '+%Y%m%d')"
          
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "PR_CHANGED" >> $GITHUB_ENV
          echo ${{ '$CHANGED' == 'true' && '$PR_ADDED' }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Issue
        if: ${{ '$CHANGED' == 'true' }}
        run: |
          ISSUE_CHANGED="### Changed\n
                         + ${{ steps.changes.outputs.CHANGED }}"
          ISSUE_DEPRECATED="### Deprecated\n
                         + ${{ steps.changes.outputs.DEPRECATED }}"
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo ${{ '$REVISED' != '{ }' && '$ISSUE_CHANGED' }} >> $GITHUB_ENV
          echo ${{ '$DEPRECATED' != '{ }' && '$ISSUE_DEPRECATED' }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create PR
        run: |
          git push --set-upstream origin monthly_check_$(date "+%Y%m%d-%H-%M")
          gh pr create \
            --repo ${{ github.repository }} \
            --assignee "$ASSIGNEES" \
            --title "Monthly LCSH check ($(date '+%Y%m%d-%H-%M'))" \
            --body "$PR_BODY")