name: monthly lcsh check
on:
  push: 
    branches:
      - github-actions
# on: 
#   schedule: 
#     - cron: '* 9 15 * *'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  ASSIGNEES: charlottekostelic
jobs:
  monthly-run:
    name: Run monthly LCSH check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set date, create branch
        run: |
          echo "DATE=$(date '+%Y%m%d-%H-%M')"
          git checkout -b monthly_check_$DATE

      - name: Run script, parse changes to vars
        run: |
          python monthly_lcsh_check.py

          echo "REVISED=$(grep 'DEBUG - Revised' lcsh.log | grep -Eo '\[.+]$')" >> $GITHUB_ENV
          echo "DEPRECATED=$(grep 'DEBUG - Deprecated' lcsh.log | grep -Eo '\[.+]$')" >> $GITHUB_ENV
          echo "NEW_INFILE=$(${{ contains(env.REVISED, 'sh') == 'true' || contains(env.DEPRECATED, 'sh') == 'true' && 'true' || 'false'}})"

      - name: Create PR Text
        run: |
          {
            echo "PR_BODY<<EOF"
            echo "### Changed:"
            echo " + lcsh.log updated with data from workflow run on $(date '+%D')"
            echo "${{ env.NEW_INFILE == 'true' && '### Added:' }}"
            echo "${{ env.NEW_INFILE == 'true' && ' + New infile is: data/acc_in.csv' }}"
            echo "${{ env.NEW_INFILE == 'true' && ' + Old infile is: data/acc_in_$DATE' }}"
            echo EOF
          } >> $GITHUB_ENV

      - name: Create Issue Text
        if: $ {{ env.NEW_INFILE == 'true' }}
        run: |
          {
            echo "ISSUE_BODY<<EOF"
            echo "${{ contains(env.DEPRECATED, 'sh') == 'true' && '### Deprecated:' }}"
            echo "${{ contains(env.DEPRECATED, 'sh') == 'true' && '$DEPRECATED' }}"
            echo "${{ contains(env.REVISED, 'sh') == 'true' && '### Changed:' }}"
            echo "${{ contains(env.REVISED, 'sh') == 'true' && '$REVISED' }}"
            echo EOF
          } >> $GITHUB_ENV

      - name: Check PR and Issue text
        run: |
          echo "PR body text is: ${{ env.PR_BODY }}"
          echo "Issue body text is: ${{ env.ISSUE_BODY }}"
